### ISSUE TITLE
Write webscraper. 

### ISSUE THREAD

**Issue by pixelatinate** [jmandzak/CatalogVisualizer#1]
Write webscraper that collects information from online catalogs in this format: https://catalog.utk.edu/preview_program.php?catoid=34&poid=16680

Will probably use beautifulsoup and selenium.

**Comment by jmandzak** [comment]
Finished part that grabs courses and milestones. Still need to finish part that grabs prereqs, coreqs, descriptions, etc.

**Comment by jmandzak** [comment]
Didn't realize there was another issue for grabbing prereqs with selenium. Closing this
